// Compiled by ClojureScript 1.9.473 {}
goog.provide('untangled.ui.menu_visuals');
goog.require('cljs.core');
goog.require('devcards.core');
goog.require('om.dom');
goog.require('om.next');
goog.require('untangled.client.core');
goog.require('untangled.ui.menu');
goog.require('untangled.i18n');
untangled.ui.menu_visuals.menu_with_item = untangled.ui.menu.menu.call(null,new cljs.core.Keyword(null,"a","a",-2123407586),"Label",new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [untangled.ui.menu.menu_item.call(null,new cljs.core.Keyword(null,"ia","ia",1614010639),"Item Label")], null));
untangled.ui.menu_visuals.menu_with_icon = untangled.ui.menu.menu.call(null,new cljs.core.Keyword(null,"a","a",-2123407586),"Label",new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [untangled.ui.menu.menu_item.call(null,new cljs.core.Keyword(null,"ia","ia",1614010639),"Item Label")], null));
untangled.ui.menu_visuals.open_menu = untangled.ui.menu.set_open_impl.call(null,untangled.ui.menu_visuals.menu_with_item,true);
untangled.ui.menu_visuals.menu_with_selection = untangled.ui.menu.select_impl.call(null,untangled.ui.menu_visuals.menu_with_item,new cljs.core.Keyword(null,"ia","ia",1614010639));
untangled.ui.menu_visuals.open_menu_with_selection = untangled.ui.menu.set_open_impl.call(null,untangled.ui.menu_visuals.menu_with_selection,true);
devcards.core.register_card.call(null,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"path","path",-188191168),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"untangled.ui.menu_visuals","untangled.ui.menu_visuals",-1362762264),new cljs.core.Keyword(null,"menu-closed","menu-closed",-1049554266)], null),new cljs.core.Keyword(null,"func","func",-238706040),(function (){
return devcards.core.card_base.call(null,new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"name","name",1843675177),"menu-closed",new cljs.core.Keyword(null,"documentation","documentation",1889593999),null,new cljs.core.Keyword(null,"main-obj","main-obj",-1544409742),untangled.ui.menu.ui_menu.call(null,untangled.ui.menu_visuals.menu_with_item),new cljs.core.Keyword(null,"initial-data","initial-data",-1315709804),cljs.core.PersistentArrayMap.EMPTY,new cljs.core.Keyword(null,"options","options",99638489),cljs.core.PersistentArrayMap.EMPTY], null));
})], null));
devcards.core.register_card.call(null,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"path","path",-188191168),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"untangled.ui.menu_visuals","untangled.ui.menu_visuals",-1362762264),new cljs.core.Keyword(null,"menu-closed-with-selection","menu-closed-with-selection",430497610)], null),new cljs.core.Keyword(null,"func","func",-238706040),(function (){
return devcards.core.card_base.call(null,new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"name","name",1843675177),"menu-closed-with-selection",new cljs.core.Keyword(null,"documentation","documentation",1889593999),null,new cljs.core.Keyword(null,"main-obj","main-obj",-1544409742),untangled.ui.menu.ui_menu.call(null,untangled.ui.menu_visuals.menu_with_selection),new cljs.core.Keyword(null,"initial-data","initial-data",-1315709804),cljs.core.PersistentArrayMap.EMPTY,new cljs.core.Keyword(null,"options","options",99638489),cljs.core.PersistentArrayMap.EMPTY], null));
})], null));
devcards.core.register_card.call(null,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"path","path",-188191168),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"untangled.ui.menu_visuals","untangled.ui.menu_visuals",-1362762264),new cljs.core.Keyword(null,"menu-open","menu-open",1430293295)], null),new cljs.core.Keyword(null,"func","func",-238706040),(function (){
return devcards.core.card_base.call(null,new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"name","name",1843675177),"menu-open",new cljs.core.Keyword(null,"documentation","documentation",1889593999),null,new cljs.core.Keyword(null,"main-obj","main-obj",-1544409742),untangled.ui.menu.ui_menu.call(null,untangled.ui.menu_visuals.open_menu),new cljs.core.Keyword(null,"initial-data","initial-data",-1315709804),cljs.core.PersistentArrayMap.EMPTY,new cljs.core.Keyword(null,"options","options",99638489),cljs.core.PersistentArrayMap.EMPTY], null));
})], null));
devcards.core.register_card.call(null,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"path","path",-188191168),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"untangled.ui.menu_visuals","untangled.ui.menu_visuals",-1362762264),new cljs.core.Keyword(null,"menu-open-with-selection","menu-open-with-selection",-131296840)], null),new cljs.core.Keyword(null,"func","func",-238706040),(function (){
return devcards.core.card_base.call(null,new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"name","name",1843675177),"menu-open-with-selection",new cljs.core.Keyword(null,"documentation","documentation",1889593999),null,new cljs.core.Keyword(null,"main-obj","main-obj",-1544409742),untangled.ui.menu.ui_menu.call(null,untangled.ui.menu_visuals.open_menu_with_selection),new cljs.core.Keyword(null,"initial-data","initial-data",-1315709804),cljs.core.PersistentArrayMap.EMPTY,new cljs.core.Keyword(null,"options","options",99638489),cljs.core.PersistentArrayMap.EMPTY], null));
})], null));
devcards.core.register_card.call(null,new cljs.core.PersistentArrayMap(null, 2, [new cljs.core.Keyword(null,"path","path",-188191168),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"untangled.ui.menu_visuals","untangled.ui.menu_visuals",-1362762264),new cljs.core.Keyword(null,"menu-icon","menu-icon",1415090604)], null),new cljs.core.Keyword(null,"func","func",-238706040),(function (){
return devcards.core.card_base.call(null,new cljs.core.PersistentArrayMap(null, 5, [new cljs.core.Keyword(null,"name","name",1843675177),"menu-icon",new cljs.core.Keyword(null,"documentation","documentation",1889593999),null,new cljs.core.Keyword(null,"main-obj","main-obj",-1544409742),untangled.ui.menu.ui_menu.call(null,untangled.ui.menu_visuals.menu_with_icon,new cljs.core.Keyword(null,"style","style",-496642736),new cljs.core.Keyword(null,"icon","icon",1679606541)),new cljs.core.Keyword(null,"initial-data","initial-data",-1315709804),cljs.core.PersistentArrayMap.EMPTY,new cljs.core.Keyword(null,"options","options",99638489),cljs.core.PersistentArrayMap.EMPTY], null));
})], null));

//# sourceMappingURL=menu_visuals.js.map?rel=1489703353336